# Generated by Django 2.0 on 2018-02-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='publiee',
            field=models.BooleanField(default=False),
        ),
    ]
