# Generated by Django 2.0 on 2018-02-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0002_annonce_publiee'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='photo',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
