# Generated by Django 2.0 on 2018-02-20 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('annonces', '0003_annonce_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
